### ISSUE TITLE
[EPIC] Test the pipeline for other sites

### ISSUE THREAD

**Issue by minump** [ncsa/ameriflux-pipeline#222]
Test the pipeline for 3 other sites for the year 2021. Data in box folder.

- [ ] Test Maize control
- [ ] Test Miscanthus control
- [ ] Test Miscanthus basalt
